const phaseWindow = (start, end, lightingPhase) => Object.freeze({
  start,
  end,
  lightingPhase,
})

const sceneMoment = ({
  id,
  name,
  region,
  position,
  target,
  captureRadius,
  angleTolerance = 28,
  landmarkId,
  time,
  effectId = null,
  timingBonus = 1.4,
  priority = 20,
}) => Object.freeze({
  id,
  name,
  region,
  position: Object.freeze(position),
  target: Object.freeze(target),
  captureRadius,
  angleTolerance,
  landmarkId,
  time,
  effectId,
  timingBonus,
  priority,
  photoType: 'scene-scene',
})

export const HOAN_KIEM_SCENE_MOMENTS = Object.freeze([
  sceneMoment({
    id: 'scene-church-puddle-reflection',
    name: 'Nhà thờ phản chiếu trong vũng nước',
    region: 'sceneChurch',
    position: [6, 0, 4],
    target: [0, 10, -27],
    captureRadius: 9,
    landmarkId: 'nhaThoLon',
    time: phaseWindow(18 * 60, 19 * 60, 'blueHour'),
    effectId: 'churchPuddle',
    timingBonus: 1.55,
  }),
  sceneMoment({
    id: 'scene-sun-between-church-towers',
    name: 'Mặt trời giữa hai tháp Nhà thờ',
    region: 'sceneChurch',
    position: [0, 0, 8],
    target: [0, 13.5, -28],
    captureRadius: 11,
    angleTolerance: 24,
    landmarkId: 'nhaThoLon',
    time: phaseWindow(17 * 60 + 15, 18 * 60, 'sunset'),
    effectId: 'churchSunDisc',
    timingBonus: 1.7,
    priority: 26,
  }),
  sceneMoment({
    id: 'scene-turtle-tower-reflection',
    name: 'Tháp Rùa phản chiếu trên Hồ Gươm',
    region: 'sceneLake',
    position: [84, 0, -86],
    target: [103, 2.4, 0],
    captureRadius: 12,
    angleTolerance: 25,
    landmarkId: 'thapRua',
    time: phaseWindow(18 * 60, 19 * 60, 'blueHour'),
    effectId: 'towerReflection',
    timingBonus: 1.65,
    priority: 25,
  }),
  sceneMoment({
    id: 'scene-the-huc-through-foliage',
    name: 'Cầu Thê Húc nhìn qua tán cây',
    region: 'sceneNgocSon',
    position: [160, 0, 60],
    target: [119, 1.2, 43.5],
    captureRadius: 11,
    landmarkId: 'cauTheHuc',
    time: phaseWindow(16 * 60 + 15, 17 * 60 + 15, 'goldenHour'),
    timingBonus: 1.5,
  }),
  sceneMoment({
    id: 'scene-tree-aisle-landmark-frame',
    name: 'Hàng cây tạo khung cho landmark',
    region: 'sceneLake',
    position: [108, 0, -91],
    target: [103, 2.4, 0],
    captureRadius: 13,
    angleTolerance: 27,
    landmarkId: 'thapRua',
    time: phaseWindow(5 * 60 + 30, 6 * 60 + 30, 'dawn'),
    effectId: 'towerReflection',
    timingBonus: 1.5,
  }),
  sceneMoment({
    id: 'scene-old-quarter-layered-signs',
    name: 'Biển hiệu Phố Cổ xếp thành nhiều lớp',
    region: 'sceneOldQuarter',
    position: [235, 0, 35],
    target: [274, 5, 36],
    captureRadius: 12,
    landmarkId: 'phoCoMoRong',
    time: phaseWindow(19 * 60, 22 * 60, 'night'),
    timingBonus: 1.45,
  }),
  sceneMoment({
    id: 'scene-sunset-wire-silhouette',
    name: 'Dây điện tạo silhouette lúc hoàng hôn',
    region: 'sceneOldQuarter',
    position: [245, 0, 35],
    target: [207, 7, 35],
    captureRadius: 13,
    angleTolerance: 30,
    landmarkId: 'phoCoMoRong',
    time: phaseWindow(17 * 60 + 15, 18 * 60, 'sunset'),
    timingBonus: 1.55,
  }),
  sceneMoment({
    id: 'scene-building-gap-light',
    name: 'Ánh sáng qua khe giữa hai tòa nhà',
    region: 'sceneOldQuarter',
    position: [245, 0, 35],
    target: [212, 5.5, 35],
    captureRadius: 13,
    angleTolerance: 26,
    landmarkId: 'phoCoMoRong',
    time: phaseWindow(16 * 60 + 15, 17 * 60 + 15, 'goldenHour'),
    effectId: 'alleyLightBeam',
    timingBonus: 1.6,
    priority: 24,
  }),
  sceneMoment({
    id: 'scene-blue-hour-lake-lights',
    name: 'Mặt hồ phản chiếu đèn vào blue hour',
    region: 'sceneLake',
    position: [58, 0, -3],
    target: [103, 1.2, 0],
    captureRadius: 12,
    landmarkId: 'hoGuom',
    time: phaseWindow(18 * 60, 19 * 60, 'blueHour'),
    effectId: 'lakeLightReflection',
    timingBonus: 1.65,
  }),
  sceneMoment({
    id: 'scene-birds-cross-landmark',
    name: 'Chim bay qua landmark',
    region: 'sceneChurch',
    position: [0, 0, 8],
    target: [0, 12, -27],
    captureRadius: 12,
    angleTolerance: 30,
    landmarkId: 'nhaThoLon',
    time: phaseWindow(5 * 60 + 30, 6 * 60 + 30, 'dawn'),
    effectId: 'landmarkBirds',
    timingBonus: 1.7,
    priority: 25,
  }),
  sceneMoment({
    id: 'scene-leaves-street-landmark-layers',
    name: 'Lá cây, phố và landmark thành ba lớp',
    region: 'sceneNgocSon',
    position: [160, 0, 60],
    target: [119, 2.8, 53.6],
    captureRadius: 12,
    angleTolerance: 30,
    landmarkId: 'denNgocSon',
    time: phaseWindow(16 * 60 + 15, 17 * 60 + 15, 'goldenHour'),
    effectId: 'foregroundLeaves',
    timingBonus: 1.6,
  }),
])
