const freezePreset = (preset) => Object.freeze({ ...preset })

export const NPC_BEHAVIORS = Object.freeze([
  'standing',
  'walker',
  'seated',
  'photographer',
])

export const NPC_PRESETS = Object.freeze({
  student: freezePreset({
    id: 'student',
    label: 'Sinh viên',
    height: 1.64,
    skin: 'skinWarm',
    top: 'cream',
    bottom: 'navy',
    shoes: 'charcoal',
    hair: 'bob',
    hairColor: 'hairBlack',
    accent: 'red',
    accessory: 'tote',
    defaultBehavior: 'walker',
    walkSpeed: 0.68,
  }),
  elderly: freezePreset({
    id: 'elderly',
    label: 'Cụ già',
    height: 1.56,
    skin: 'skinWarm',
    top: 'olive',
    bottom: 'brown',
    shoes: 'darkBrown',
    hair: 'short',
    hairColor: 'hairGray',
    accent: 'oldYellow',
    accessory: 'cane',
    defaultBehavior: 'standing',
    walkSpeed: 0.42,
  }),
  tourist: freezePreset({
    id: 'tourist',
    label: 'Khách du lịch',
    height: 1.73,
    skin: 'skinLight',
    top: 'mustard',
    bottom: 'denim',
    shoes: 'white',
    hair: 'cap',
    hairColor: 'hairBrown',
    accent: 'teal',
    accessory: 'camera',
    defaultBehavior: 'photographer',
    walkSpeed: 0.62,
  }),
  officeWorker: freezePreset({
    id: 'officeWorker',
    label: 'Người đi làm',
    height: 1.69,
    skin: 'skinWarm',
    top: 'blue',
    bottom: 'charcoal',
    shoes: 'darkBrown',
    hair: 'short',
    hairColor: 'hairBlack',
    accent: 'brown',
    accessory: null,
    defaultBehavior: 'standing',
    walkSpeed: 0.64,
  }),
  middleAged: freezePreset({
    id: 'middleAged',
    label: 'Khách trung niên',
    height: 1.62,
    skin: 'skinDeep',
    top: 'terracotta',
    bottom: 'brown',
    shoes: 'charcoal',
    hair: 'bun',
    hairColor: 'hairBrown',
    accent: 'cream',
    accessory: null,
    defaultBehavior: 'standing',
    walkSpeed: 0.52,
  }),
  teaVendor: freezePreset({
    id: 'teaVendor',
    label: 'Cô bán trà',
    height: 1.57,
    skin: 'skinDeep',
    top: 'blue',
    bottom: 'darkBrown',
    shoes: 'charcoal',
    hair: 'conicalHat',
    hairColor: 'hairBlack',
    accent: 'straw',
    accessory: 'basket',
    defaultBehavior: 'standing',
    walkSpeed: 0.48,
  }),
  motorbikeDriver: freezePreset({
    id: 'motorbikeDriver',
    label: 'Người lái xe máy',
    height: 1.7,
    skin: 'skinWarm',
    top: 'teal',
    bottom: 'denim',
    shoes: 'charcoal',
    hair: 'helmet',
    hairColor: 'hairBlack',
    accent: 'red',
    accessory: null,
    defaultBehavior: 'seated',
    walkSpeed: 0.6,
  }),
  child: freezePreset({
    id: 'child',
    label: 'Em nhỏ',
    height: 1.27,
    skin: 'skinWarm',
    top: 'terracotta',
    bottom: 'navy',
    shoes: 'white',
    hair: 'short',
    hairColor: 'hairBlack',
    accent: 'mustard',
    accessory: 'backpack',
    defaultBehavior: 'walker',
    walkSpeed: 0.76,
  }),
  churchVisitor: freezePreset({
    id: 'churchVisitor',
    label: 'Khách Nhà thờ',
    height: 1.67,
    skin: 'skinLight',
    top: 'maroon',
    bottom: 'charcoal',
    shoes: 'darkBrown',
    hair: 'bun',
    hairColor: 'hairBrown',
    accent: 'cream',
    accessory: null,
    defaultBehavior: 'standing',
    walkSpeed: 0.56,
  }),
  priest: freezePreset({
    id: 'priest',
    label: 'Linh mục',
    height: 1.75,
    skin: 'skinWarm',
    top: 'black',
    bottom: 'black',
    shoes: 'darkBrown',
    hair: 'short',
    hairColor: 'hairGray',
    accent: 'white',
    accessory: 'collar',
    defaultBehavior: 'standing',
    walkSpeed: 0.52,
  }),
})

export const NPC_PRESET_NAMES = Object.freeze(Object.keys(NPC_PRESETS))

export function getNpcPreset(name = 'student') {
  const preset = NPC_PRESETS[name]
  if (!preset) {
    throw new RangeError(`Unknown NPC preset: ${name}`)
  }
  return preset
}
