function deepFreeze(value) {
  if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value
  for (const child of Object.values(value)) deepFreeze(child)
  return Object.freeze(value)
}

function defineProfile(profile) {
  const {
    proportions,
    head,
    face,
    hair,
    collider,
  } = profile
  return deepFreeze({
    ...profile,
    faceMode: face.mode,
    skinColor: head.skinColor,
    hairColor: hair.color,
    bodyWidth: proportions.bodyWidth,
    limbBulk: proportions.limbBulk,
    colliderRadius: collider.radius,
    colliderDepth: collider.depth,
  })
}

export const SPECIAL_NPC_PROFILES = deepFreeze({
  gymmer: defineProfile({
    id: 'gymmer',
    label: 'Anh kính cười',
    height: 1.78,
    focusRatio: 0.84,
    defaultOutfit: 'wineStreet',
    proportions: {
      bodyWidth: 1.08,
      shoulderWidth: 1.115,
      torsoWidth: 1.06,
      torsoDepth: 1,
      hipWidth: 0.98,
      limbBulk: 1.08,
      armLength: 1,
      legLength: 1,
      handScale: 1,
      footScale: [1.02, 1, 1.03],
    },
    head: {
      position: [0, 1.53, 0],
      scale: [0.38, 0.462, 0.36],
      skinColor: 0xc98762,
      shadeColor: 0xa9674a,
      flatShading: true,
      neck: {
        position: [0, 1.35, 0],
        scale: [0.17, 0.14, 0.17],
      },
    },
    face: {
      mode: 'procedural',
      expression: 'wideSmile',
      exaggeration: 0.82,
      eyes: {
        spacing: 0.19,
        positionY: 0.04,
        scale: [0.052, 0.038, 0.026],
        irisColor: 0x2a2019,
        scleraColor: 0xf1e8db,
      },
      brows: {
        style: 'raisedFriendly',
        color: 0x171719,
        width: 0.115,
        thickness: 0.022,
        positionY: 0.115,
        arch: 0.035,
      },
      nose: {
        style: 'faceted',
        position: [0, -0.015, 0.19],
        scale: [0.06, 0.105, 0.07],
      },
      mouth: {
        style: 'wideOpenSmile',
        positionY: -0.13,
        width: 0.255,
        height: 0.095,
        curve: 0.8,
        lipColor: 0x9f514d,
        interiorColor: 0x4b2425,
        teethVisible: true,
        teethColor: 0xf2e8cf,
        teethRows: 1,
      },
    },
    hair: {
      style: 'spiky',
      color: 0x161719,
      position: [0, 0.12, -0.045],
      scale: [0.43, 0.27, 0.4],
      spikeCount: 7,
    },
    glasses: {
      enabled: true,
      style: 'rectangular',
      position: [0, 0.025, 0.195],
      scale: [1.04, 1, 1],
      rotation: [0, 0, 0],
      frameColor: 0x202226,
      lensColor: 0x75828a,
      lensOpacity: 0.16,
      frameThickness: 0.025,
      bridgeWidth: 0.075,
      templeLength: 0.25,
    },
    outfit: {
      id: 'wineStreet',
      top: {
        style: 'shortSleeveShirt',
        color: 0x743947,
        shadeColor: 0x552a35,
        sleeveLength: 0.32,
        collar: 'open',
      },
      bottom: {
        style: 'straightPants',
        color: 0x303238,
        shadeColor: 0x22242a,
        length: 'full',
      },
      shoes: {
        style: 'lowSneaker',
        color: 0x1d2024,
        soleColor: 0xd8d0bf,
      },
    },
    accessories: {
      backpack: null,
      ball: null,
    },
    animation: {
      idlePose: 'friendlyRelaxed',
      breathing: {
        speed: 1.28,
        amplitude: 0.0035,
      },
      lookAt: {
        radius: 4.2,
        turnSpeed: 2.7,
        maxYaw: Math.PI * 0.62,
      },
      celebration: {
        enabled: true,
        cycleLength: 9,
        raiseStart: 5.4,
        holdStart: 6,
        lowerStart: 6.9,
        end: 7.6,
        leftShoulderZ: -1.45,
        rightShoulderZ: 1.45,
        leftElbowZ: -1.05,
        rightElbowZ: 1.05,
      },
      walk: {
        enabled: false,
        stride: 0,
        armSwing: 0,
      },
    },
    collider: {
      radius: 0.3,
      depth: 0.23,
      height: 1.72,
      centerY: 0.86,
      includeAccessories: false,
    },
  }),
  basketball: defineProfile({
    id: 'basketball',
    label: 'Cầu thủ Elite',
    // 1.95 m is about 9.6% taller than the 1.78 m character above.
    height: 1.95,
    focusRatio: 0.84,
    defaultOutfit: 'darkCourt',
    proportions: {
      bodyWidth: 1.02,
      shoulderWidth: 1.04,
      torsoWidth: 1,
      torsoDepth: 0.98,
      hipWidth: 0.98,
      limbBulk: 1.02,
      armLength: 1.04,
      legLength: 1.08,
      handScale: 1.02,
      footScale: [1.08, 1.06, 1.12],
    },
    head: {
      position: [0, 1.53, 0],
      scale: [0.37, 0.47, 0.35],
      skinColor: 0xcd8a63,
      shadeColor: 0xaa684c,
      flatShading: true,
      neck: {
        position: [0, 1.35, 0],
        scale: [0.17, 0.14, 0.17],
      },
    },
    face: {
      mode: 'procedural',
      expression: 'calm',
      exaggeration: 0.46,
      eyes: {
        spacing: 0.185,
        positionY: 0.035,
        scale: [0.052, 0.032, 0.025],
        irisColor: 0x2b211c,
        scleraColor: 0xeee6db,
        lidAmount: 0.22,
      },
      brows: {
        style: 'softStraight',
        color: 0x3d2a22,
        width: 0.112,
        thickness: 0.018,
        positionY: 0.105,
        arch: 0.012,
      },
      nose: {
        style: 'faceted',
        position: [0, -0.018, 0.188],
        scale: [0.058, 0.1, 0.068],
      },
      mouth: {
        style: 'calmClosed',
        positionY: -0.125,
        width: 0.175,
        height: 0.035,
        curve: 0.08,
        lipColor: 0x9d5d5b,
        interiorColor: 0x6d3838,
        teethVisible: false,
        teethColor: 0xeee4cf,
        teethRows: 0,
      },
    },
    hair: {
      style: 'tousled',
      color: 0x5a3826,
      position: [0, 0.115, -0.045],
      scale: [0.42, 0.26, 0.39],
      spikeCount: 6,
    },
    glasses: {
      enabled: true,
      style: 'thinRounded',
      position: [0, 0.02, 0.192],
      scale: [1.02, 0.96, 1],
      rotation: [0, 0, -0.025],
      frameColor: 0x26282b,
      lensColor: 0x9ca7aa,
      lensOpacity: 0.12,
      frameThickness: 0.014,
      bridgeWidth: 0.07,
      templeLength: 0.245,
    },
    outfit: {
      id: 'darkCourt',
      top: {
        style: 'layeredAthletic',
        color: 0x20242a,
        shadeColor: 0x15181c,
        sleeveLength: 0.34,
        collar: 'crew',
        layers: [
          {
            style: 'undershirt',
            color: 0x171a1e,
            depthOffset: 0,
          },
          {
            style: 'openOvershirt',
            color: 0x30353c,
            depthOffset: 0.018,
          },
        ],
      },
      bottom: {
        style: 'taperedPants',
        color: 0x202329,
        shadeColor: 0x15171b,
        length: 'full',
      },
      shoes: {
        style: 'basketballHighTop',
        color: 0x25292f,
        panelColor: 0x565d66,
        accentColor: 0xa64b3f,
        soleColor: 0xddd8cc,
      },
    },
    accessories: {
      backpack: {
        enabled: true,
        style: 'elite',
        color: 0x4f5d48,
        trimColor: 0x2f3730,
        badgeColor: 0x8e443c,
        position: [0, 1.03, -0.26],
        scale: [0.43, 0.55, 0.24],
        strapColor: 0x4f5d48,
      },
      ball: {
        enabled: true,
        style: 'lowPolyBasketball',
        geometry: 'sphere',
        color: 0xc9692c,
        seamColor: 0x191b1e,
        radius: 0.23,
        handOffset: [0, -0.02, 0.2],
        heldBy: 'rightHand',
        seamCount: 3,
      },
    },
    animation: {
      idlePose: 'holdBall',
      breathing: {
        speed: 1.18,
        amplitude: 0.0032,
      },
      lookAt: {
        radius: 4.5,
        turnSpeed: 2.45,
        maxYaw: Math.PI * 0.58,
      },
      walk: {
        enabled: false,
        stride: 0,
        armSwing: 0,
      },
      armPose: {
        leftShoulder: [-0.12, 0, -0.05],
        leftElbow: [-0.18, 0, 0.08],
        rightShoulder: [-0.62, 0, 0.16],
        rightElbow: [-0.78, 0, -0.52],
      },
    },
    collider: {
      radius: 0.35,
      depth: 0.29,
      height: 1.89,
      centerY: 0.945,
      includeAccessories: false,
    },
  }),
  mo: defineProfile({
    id: 'mo',
    label: 'Mơ',
    height: 1.7,
    focusRatio: 0.83,
    defaultOutfit: 'idle',
    proportions: {
      bodyWidth: 0.9,
      shoulderWidth: 0.86,
      torsoWidth: 0.88,
      torsoDepth: 0.9,
      hipWidth: 0.9,
      limbBulk: 0.86,
      armLength: 0.98,
      legLength: 0.98,
      handScale: 0.9,
      footScale: [0.92, 0.92, 0.95],
    },
    head: {
      position: [0, 1.53, 0],
      scale: [0.39, 0.44, 0.36],
      skinColor: 0xd79b76,
      shadeColor: 0xb87859,
      flatShading: true,
      neck: {
        position: [0, 1.35, 0],
        scale: [0.155, 0.13, 0.155],
      },
    },
    face: {
      mode: 'procedural',
      expression: 'gentleSmile',
      exaggeration: 0.62,
      eyes: {
        spacing: 0.18,
        positionY: 0.045,
        scale: [0.055, 0.04, 0.026],
        irisColor: 0x2a211d,
        scleraColor: 0xf1e8df,
      },
      brows: {
        style: 'softArc',
        color: 0x2b201d,
        width: 0.11,
        thickness: 0.017,
        positionY: 0.112,
        arch: 0.026,
      },
      nose: {
        style: 'smallFaceted',
        position: [0, -0.012, 0.19],
        scale: [0.052, 0.09, 0.06],
      },
      mouth: {
        style: 'gentleSmile',
        positionY: -0.12,
        width: 0.17,
        height: 0.045,
        curve: 0.42,
        lipColor: 0xa85f5c,
        interiorColor: 0x6b3437,
        teethVisible: false,
        teethColor: 0xeee4d1,
        teethRows: 0,
      },
    },
    hair: {
      style: 'longVolumetric',
      color: 0x211b1a,
      position: [0, 0.06, -0.08],
      scale: [0.46, 0.3, 0.42],
    },
    glasses: {
      enabled: true,
      style: 'sunglassesOnHead',
      position: [0, 0.295, 0.035],
      scale: [1.05, 0.9, 1],
      rotation: [-0.24, 0, 0],
      frameColor: 0x29282a,
      lensColor: 0x34383e,
      lensOpacity: 0.72,
      frameThickness: 0.024,
      bridgeWidth: 0.07,
      templeLength: 0.14,
    },
    outfit: {
      id: 'idle',
      top: {
        style: 'camisole',
        color: 0xdedbd1,
        shadeColor: 0xc7c3ba,
        strapColor: 0xe6e2d7,
        strapWidth: 0.045,
        neckline: 'straight',
      },
      bottom: {
        style: 'shorts',
        color: 0x30465c,
        shadeColor: 0x233547,
        length: 'short',
      },
      shoes: {
        style: 'simpleSneaker',
        color: 0x272b31,
        soleColor: 0xd7d2c7,
      },
    },
    outfitVariants: {
      church: {
        id: 'church',
        top: {
          style: 'camisole',
          color: 0xd3d0c7,
          shadeColor: 0xbdb9b0,
          strapColor: 0xe1ddd2,
          strapWidth: 0.045,
          neckline: 'straight',
        },
        bottom: {
          style: 'shorts',
          color: 0x293d50,
          shadeColor: 0x1f3040,
          length: 'short',
        },
        shoes: {
          style: 'simpleSneaker',
          color: 0x34373c,
          soleColor: 0xc9c4ba,
        },
      },
    },
    accessories: {
      backpack: null,
      ball: null,
    },
    animation: {
      idlePose: 'gentle',
      breathing: {
        speed: 1.32,
        amplitude: 0.0036,
      },
      lookAt: {
        radius: 4,
        turnSpeed: 2.55,
        maxYaw: Math.PI * 0.42,
      },
      walk: {
        enabled: true,
        stride: 0.34,
        strideSpeed: 6.4,
        armSwing: 0.2,
        footLift: 0.045,
        kneeBend: 0.3,
      },
      armPose: {
        leftShoulder: [-0.12, 0, -0.055],
        leftElbow: [-0.28, 0, 0.1],
        rightShoulder: [-0.12, 0, 0.055],
        rightElbow: [-0.28, 0, -0.1],
      },
    },
    collider: {
      radius: 0.25,
      depth: 0.2,
      height: 1.64,
      centerY: 0.82,
      includeAccessories: false,
    },
  }),
})

export const SPECIAL_NPC_PROFILE_NAMES = Object.freeze(
  Object.keys(SPECIAL_NPC_PROFILES),
)

export function getSpecialNpcProfile(id) {
  const profile = SPECIAL_NPC_PROFILES[id]
  if (!profile) throw new RangeError(`Unknown special NPC profile: ${id}`)
  return profile
}
