export const PHOTO_QUEST_STATUS = Object.freeze({
  LOCKED: 'locked',
  ACTIVE: 'active',
  COMPLETED: 'completed',
})

const timeWindow = (start, end, phases = []) => Object.freeze({
  start,
  end,
  phases: Object.freeze([...phases]),
})

const location = (label, districtIds = []) => Object.freeze({
  label,
  mapId: 'hoanKiem',
  districtIds: Object.freeze([...districtIds]),
})

const quest = ({
  id,
  name,
  description,
  subject,
  eventIds = [],
  sceneMomentIds = [],
  subjectIds = [],
  landmarkIds = [],
  location: questLocation,
  time,
  climaxRequired = true,
  minimumScore,
}) => Object.freeze({
  id,
  name,
  description,
  subject,
  eventIds: Object.freeze([...eventIds]),
  sceneMomentIds: Object.freeze([...sceneMomentIds]),
  subjectIds: Object.freeze([...subjectIds]),
  landmarkIds: Object.freeze([...landmarkIds]),
  location: questLocation,
  time,
  climaxRequired,
  minimumScore,
})

const group = (id, name, description, quests) => Object.freeze({
  id,
  name,
  description,
  quests: Object.freeze(quests),
})

export const PHOTO_QUEST_GROUPS = Object.freeze([
  group(
    'hanoi-dawn',
    'Bình minh Hà Nội',
    'Những nhịp chuyển động và mặt nước đầu ngày.',
    [
      quest({
        id: 'dawn-church-birds',
        name: 'Cánh chim trước tháp chuông',
        description: 'Bắt đàn chim đi qua mặt tiền Nhà thờ trong đúng scene moment.',
        subject: 'Đàn chim và Nhà thờ Lớn',
        sceneMomentIds: ['scene-birds-cross-landmark'],
        landmarkIds: ['nhaThoLon'],
        location: location('Sân Nhà thờ Lớn', ['churchDistrict', 'sceneChurch']),
        time: timeWindow(5 * 60 + 30, 6 * 60 + 30, ['dawn']),
        climaxRequired: true,
        minimumScore: 58,
      }),
      quest({
        id: 'dawn-lake-exercise',
        name: 'Khởi động bên hồ',
        description: 'Chụp đủ nhóm tập thể dục khi động tác đồng bộ đạt cao trào.',
        subject: 'Nhóm tập thể dục Hồ Gươm',
        eventIds: ['lake-morning-exercise'],
        subjectIds: [
          'Người tập thể dục ven hồ 1',
          'Người tập thể dục ven hồ 2',
          'Người tập thể dục ven hồ 3',
        ],
        location: location('Bờ tây Hồ Gươm', ['hoanKiemDistrict']),
        time: timeWindow(5 * 60 + 30, 8 * 60 + 15, ['dawn', 'day']),
        climaxRequired: true,
        minimumScore: 62,
      }),
      quest({
        id: 'dawn-landmark-reflection',
        name: 'Landmark trong mặt nước sớm',
        description: 'Dùng hàng cây làm khung cho Tháp Rùa và phần phản chiếu lúc bình minh.',
        subject: 'Tháp Rùa và reflection Hồ Gươm',
        sceneMomentIds: ['scene-tree-aisle-landmark-frame'],
        landmarkIds: ['thapRua'],
        location: location('Bờ nam Hồ Gươm', ['hoanKiemDistrict', 'sceneLake']),
        time: timeWindow(5 * 60 + 30, 6 * 60 + 30, ['dawn']),
        climaxRequired: true,
        minimumScore: 64,
      }),
    ],
  ),
  group(
    'hanoi-rhythm',
    'Nhịp sống Hà Nội',
    'Những trao đổi nhỏ làm nên nhịp phố.',
    [
      quest({
        id: 'rhythm-flower-gift',
        name: 'Bó hoa được trao',
        description: 'Chụp đúng lúc người bán hoa trao bó hoa cho khách.',
        subject: 'Người trao và người nhận hoa',
        eventIds: ['church-flower-gift'],
        subjectIds: ['Bạn trẻ 1', 'Bạn trẻ 2'],
        location: location('Sân Nhà thờ Lớn', ['churchDistrict']),
        time: timeWindow(8 * 60, 16 * 60 + 45, ['day', 'goldenHour']),
        climaxRequired: true,
        minimumScore: 64,
      }),
      quest({
        id: 'rhythm-old-quarter-delivery',
        name: 'Chuyến hàng Phố Cổ',
        description: 'Bắt khoảnh khắc kiện hàng chuyển từ người giao sang chủ quán.',
        subject: 'Người giao hàng và chủ quán',
        eventIds: ['old-quarter-delivery-handoff'],
        subjectIds: ['Người đi bộ ven hồ 1', 'Du khách Phố Cổ 2'],
        location: location('Cửa hàng Phố Cổ', ['oldQuarterConnector']),
        time: timeWindow(8 * 60, 17 * 60 + 30, ['day', 'goldenHour', 'sunset']),
        climaxRequired: true,
        minimumScore: 65,
      }),
      quest({
        id: 'rhythm-ice-cream',
        name: 'Que kem đầu tiên',
        description: 'Chụp người lớn trao kem cho em nhỏ tại phố đi bộ.',
        subject: 'Phụ huynh và em nhỏ nhận kem',
        eventIds: ['pedestrian-ice-cream-parent-child'],
        subjectIds: ['Phụ huynh mua kem', 'Em nhỏ nhận kem'],
        location: location('Khu bán kem phố đi bộ', ['pedestrianDistrict']),
        time: timeWindow(14 * 60, 21 * 60 + 30, ['day', 'goldenHour', 'sunset', 'blueHour', 'night']),
        climaxRequired: true,
        minimumScore: 63,
      }),
      quest({
        id: 'rhythm-church-cyclist',
        name: 'Một vòng bánh xe',
        description: 'Giữ người đạp xe rõ nét khi băng qua quảng trường Nhà thờ.',
        subject: 'Người đạp xe',
        eventIds: ['church-cyclist-crossing'],
        subjectIds: ['Người đi dạo phía sân'],
        location: location('Quảng trường Nhà thờ Lớn', ['churchDistrict']),
        time: timeWindow(7 * 60, 9 * 60 + 30, ['day']),
        climaxRequired: false,
        minimumScore: 60,
      }),
    ],
  ),
  group(
    'encounters',
    'Những cuộc gặp gỡ',
    'Sự quan tâm và kết nối giữa người với người.',
    [
      quest({
        id: 'encounter-bike-help',
        name: 'Một tay dựng xe',
        description: 'Chụp trọn cả người giúp và người được giúp tại Phố Cổ.',
        subject: 'Hai người cùng dựng xe',
        eventIds: ['old-quarter-bike-help'],
        subjectIds: ['Chú xe ôm phố cổ', 'Du khách Phố Cổ 1'],
        location: location('Ngã phố Phố Cổ', ['oldQuarterConnector']),
        time: timeWindow(8 * 60, 19 * 60, ['day', 'goldenHour', 'sunset', 'blueHour']),
        climaxRequired: true,
        minimumScore: 66,
      }),
      quest({
        id: 'encounter-portrait-handoff',
        name: 'Bức chân dung hoàn thành',
        description: 'Chụp đúng lúc họa sĩ trao tranh cho người làm mẫu.',
        subject: 'Họa sĩ và khách nhận tranh',
        eventIds: ['pedestrian-portrait-session'],
        subjectIds: ['Họa sĩ chân dung phố đi bộ', 'Khách làm mẫu chân dung'],
        location: location('Khu vẽ chân dung phố đi bộ', ['pedestrianDistrict']),
        time: timeWindow(8 * 60, 18 * 60 + 30, ['day', 'goldenHour', 'sunset', 'blueHour']),
        climaxRequired: true,
        minimumScore: 68,
      }),
      quest({
        id: 'encounter-tourist-photo-help',
        name: 'Người lạ sau ống kính',
        description: 'Ghi lại khoảnh khắc người lạ giúp du khách chụp ảnh trên cầu.',
        subject: 'Du khách và người giúp chụp ảnh',
        eventIds: ['bridge-stranger-photo-help'],
        subjectIds: ['Du khách nhờ chụp ảnh trên cầu', 'Người lạ giúp chụp ảnh trên cầu'],
        location: location('Cầu Thê Húc', ['theHucBridge']),
        time: timeWindow(8 * 60, 19 * 60, ['day', 'goldenHour', 'sunset', 'blueHour']),
        climaxRequired: true,
        minimumScore: 67,
      }),
      quest({
        id: 'encounter-adult-child',
        name: 'Cùng nhìn về một hướng',
        description: 'Đưa người lớn, trẻ em và cảnh được chỉ vào cùng một khung hình.',
        subject: 'Người lớn chỉ cảnh cho trẻ em',
        eventIds: ['bridge-adult-points-view'],
        subjectIds: ['Người lớn chỉ cảnh trên cầu', 'Em nhỏ ngắm cảnh trên cầu'],
        location: location('Cầu Thê Húc', ['theHucBridge']),
        time: timeWindow(8 * 60, 18 * 60 + 30, ['day', 'goldenHour', 'sunset', 'blueHour']),
        climaxRequired: true,
        minimumScore: 66,
      }),
    ],
  ),
  group(
    'last-light',
    'Ánh sáng cuối ngày',
    'Hoàng hôn, blue hour và một tấm ảnh tự do thật sự nổi bật.',
    [
      quest({
        id: 'last-light-pedestrian-dance',
        name: 'Phố đi bộ vào nhịp',
        description: 'Chụp động tác cao trào của nhóm nhảy trong ánh hoàng hôn.',
        subject: 'Nhóm nhảy đường phố',
        eventIds: ['pedestrian-street-dance'],
        subjectIds: [
          'Vũ công phố đi bộ 1',
          'Vũ công phố đi bộ 2',
          'Vũ công phố đi bộ 3',
        ],
        location: location('Sân biểu diễn phố đi bộ', ['pedestrianDistrict']),
        time: timeWindow(17 * 60 + 15, 18 * 60, ['sunset']),
        climaxRequired: true,
        minimumScore: 70,
      }),
      quest({
        id: 'last-light-the-huc-blue-hour',
        name: 'Bóng người trên cầu đỏ',
        description: 'Chụp silhouette trên Cầu Thê Húc trong blue hour.',
        subject: 'Bóng người và Cầu Thê Húc',
        eventIds: ['bridge-blue-hour-silhouette'],
        subjectIds: ['Bóng người trên Cầu Thê Húc'],
        landmarkIds: ['cauTheHuc'],
        location: location('Cầu Thê Húc', ['theHucBridge']),
        time: timeWindow(18 * 60, 19 * 60, ['blueHour']),
        climaxRequired: true,
        minimumScore: 70,
      }),
      quest({
        id: 'last-light-turtle-reflection',
        name: 'Tháp Rùa lên đèn',
        description: 'Đặt trọn Tháp Rùa và reflection trong đúng scene moment blue hour.',
        subject: 'Tháp Rùa phản chiếu trên Hồ Gươm',
        sceneMomentIds: ['scene-turtle-tower-reflection'],
        landmarkIds: ['thapRua'],
        location: location('Điểm ngắm Tháp Rùa', ['hoanKiemDistrict', 'sceneLake']),
        time: timeWindow(18 * 60, 19 * 60, ['blueHour']),
        climaxRequired: true,
        minimumScore: 72,
      }),
      quest({
        id: 'last-light-free-best',
        name: 'Tấm ảnh của riêng bạn',
        description: 'Một ảnh tự do tại Hoàn Kiếm, chụp trong ánh sáng cuối ngày và đạt chất lượng cao.',
        subject: 'Tự do lựa chọn',
        location: location('Khu Hoàn Kiếm'),
        time: timeWindow(16 * 60 + 15, 19 * 60, ['goldenHour', 'sunset', 'blueHour']),
        climaxRequired: false,
        minimumScore: 82,
      }),
    ],
  ),
])
